MongoApp/Controllers/DeleteController.cs
using Microsoft.AspNetCore.Mvc;
using MongoApp.DTO.DeleteDto;
using MongoApp.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;

namespace MongoApp.Controllers
{
    public class DeleteController : Controller
    {
        public readonly HttpClient _httpClient;
        public DeleteController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient("MyApiClient");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(DeleteDto user, bool isAdminDelete = false)
        {
            try
            {
                var json = JsonConvert.SerializeObject(user);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var request = new HttpRequestMessage
                {
                    Method = HttpMethod.Put,
                    Content = content,
                    RequestUri = new Uri("api/UserData/DeactivateUser", UriKind.Relative)
                };

                var response = await _httpClient.SendAsync(request);
                if (response.IsSuccessStatusCode)
                {
                    TempData["ToastMessage"] = "User Deleted Successfully";
                    ViewBag.ToastMessage = TempData["ToastMessage"]?.ToString();

                    if (isAdminDelete)
                    {
                        return RedirectToAction("GetAllUser", "GetAllUser");
                    }
                    else
                    {
                        return RedirectToAction("Logout", "Logout");
                    }
                }
                else
                {
                    return View("Error", response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }

        [HttpPost]
        public IActionResult DeleteUser1(UserData user)
        {
            try
            {
                var x = new DeleteDto()
                {
                    Id = user.Id,
                    Password = user.Password
                };
                return View("DeleteForSure", x);
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }

        [HttpPost]
        public IActionResult AdminDeleteUser1(UserData user)
        {
            try
            {
                var x = new DeleteDto()
                {
                    Id = user.Id,
                    Password = user.Password
                };
                return View("AdminDeleteForSure", x);
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }
    }
}

MongoApp/Controllers/PrivacyController.cs
using Microsoft.AspNetCore.Mvc;

namespace MongoApp.Controllers
{
    public class PrivacyController : Controller
    {
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

MongoApp/Controllers/UpdateController.cs
using Microsoft.AspNetCore.Mvc;
using MongoApp.DTO.UpdateDto;
using MongoApp.Models;
using Newtonsoft.Json;
using System.Net;
using System.Text;

namespace MongoApp.Controllers
{
    public class UpdateController : Controller
    {
        HttpClient _httpClient;
        public UpdateController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient("MyApiClient");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateUser(UserUpdateDto user)
        {
            try
            {
                var json = JsonConvert.SerializeObject(user);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var response = await _httpClient.PutAsync("api/UserData/UpdateUser", content);
                if (response.IsSuccessStatusCode)
                {
                    var responseBody = await response.Content.ReadAsStringAsync();
                    var updatedUser = JsonConvert.DeserializeObject<UserData>(responseBody);
                    TempData["ToastMessage"] = "User Updated Successfully.";
                    ViewBag.ToastMessage = TempData["ToastMessage"]?.ToString();
                    if (updatedUser.Role == "Admin")
                    {
                        return View("~/Views/Login/Admin/AdminProfile.cshtml", updatedUser);
                    }
                    return View("~/Views/Login/User/UserProfile.cshtml", updatedUser);
                }
                else if (response.StatusCode == HttpStatusCode.Conflict)
                {
                    TempData["ToastMessage"] = "User Email or User Name Already Exists. Pls Try Again.";
                    return RedirectToAction("UpdateUser", user);
                }
                else
                {
                    TempData["ToastMessage"] = "Some Unknown Error occured. Pls Try Again.";
                    return RedirectToAction("UpdateUser", user);
                }
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }
        [HttpPost]
        public IActionResult UpdateUser1(UserData user)
        {
            try
            {
                var x = new UserUpdateDto()
                {
                    Id = user.Id,
                    UserName = user.UserName,
                    Age = user.Age,
                    Name = user.Name,
                    Email = user.Email,
                    Password = user.Password,
                    Phonenumber = user.Phonenumber,
                    Role = user.Role,
                    Status = user.Status,
                };
                ViewBag.ToastMessage = TempData["ToastMessage"]?.ToString();
                return View("UpdateUser", x);
            }
            catch (Exception ex)
            {

                return View("Error", ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AdminUpdateUser(AdminUpdateDto user)
        {
            try
            {
                var json = JsonConvert.SerializeObject(user);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var response = await _httpClient.PutAsync("api/UserData/UpdateUser", content);
                if (response.IsSuccessStatusCode)
                {
                    TempData["ToastMessage"] = "User updated successfully!";
                    return RedirectToAction("GetAllUser", "GetAllUser");
                }
                else if (response.StatusCode == HttpStatusCode.Conflict)
                {
                    TempData["ToastMessage"] = "User Email or User Name Already Exists. Pls Try Again.";
                    ViewBag.ToastMessage = TempData["ToastMessage"]?.ToString();
                    return View("AdminUpdateUser", user);
                }
                else
                {
                    return View("Error", response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }
        [HttpPost]
        public IActionResult AdminUpdateUser1(UserData user)
        {
            try
            {
                var x = new AdminUpdateDto()
                {
                    Id = user.Id,
                    UserName = user.UserName,
                    Age = user.Age,
                    Name = user.Name,
                    Email = user.Email,
                    Password = user.Password,
                    Phonenumber = user.Phonenumber,
                    Role = user.Role,
                    Status = user.Status,
                };
                ViewBag.ToastMessage = TempData["ToastMessage"]?.ToString();
                return View("AdminUpdateUser", x);
            }
            catch (Exception ex)
            {

                return View("Error", ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePassword(UpdatePasswordDto dto)
        {
            try
            {
                var json = JsonConvert.SerializeObject(dto);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var response = await _httpClient.PutAsync("api/UserData/UpdateUserPassword", content);
                if (response.IsSuccessStatusCode)
                {
                    return View("PasswordUpdateResponse");
                }
                else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                {
                    TempData["UpdateMessage"] = "Wrong Current Password. Pls Try Again.";
                    return RedirectToAction("UpdatePassword1", dto.Id);
                }
                else return BadRequest(response.ReasonPhrase);
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }
        [HttpPost]
        public IActionResult UpdatePassword1(string Id)
        {
            var x = new UpdatePasswordDto { Id = Id };
            ViewBag.ToastMessage = TempData["UpdateMessage"]?.ToString();
            return View("UpdatePassword", x);
        }
    }
}

MongoApp/Views/Shared/_Alter2Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UserAuthCaller</title>
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MongoApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Login">User</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
                        aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarContent">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Login" title="Home">
                                <i class="bi bi-house-fill"></i> Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Privacy" asp-action="Privacy" title="Privacy Policy">
                                <i class="bi bi-shield-fill-exclamation"></i> Privacy
                            </a>
                        </li>
                    </ul>

                    <!-- Wrap the dropdown li element with a div and apply ms-auto class -->
                    <div class="ms-auto">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown"
                                   aria-expanded="false" title="User Actions">
                                    <img src="\profile.jpg" style="width: 50px; height: 50px; border-radius: 70%;">
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="userDropdown">
                                    <li>
                                        <form action="@Url.Action("UpdateUser1", "Update")" method="post">
                                            <input type="hidden" name="Id" value="@Model.Id" />
                                            <input type="hidden" name="UserName" value="@Model.UserName" />
                                            <input type="hidden" name="Age" value="@Model.Age" />
                                            <input type="hidden" name="Name" value="@Model.Name" />
                                            <input type="hidden" name="Email" value="@Model.Email" />
                                            <input type="hidden" name="Phonenumber" value="@Model.Phonenumber" />
                                            <input type="hidden" name="Password" value="@Model.Password" />
                                            <input type="hidden" name="Role" value="@Model.Role" />
                                            <input type="hidden" name="Status" value="@Model.Status" />
                                            @Html.AntiForgeryToken()
                                            <button type="submit" class="dropdown-item">
                                                <i class="bi bi-person-badge"></i> Edit Profile
                                            </button>
                                        </form>
                                    </li>
                                    <li>
                                        <form action="@Url.Action("UpdatePassword1", "Update")" method="post">
                                            <input type="hidden" name="Id" value="@Model.Id" />
                                            @Html.AntiForgeryToken()
                                            <button type="submit" class="dropdown-item">
                                                <i class="bi bi-key-fill"></i> Change Password
                                            </button>
                                        </form>
                                    </li>
                                    <li>
                                        <form action="@Url.Action("DeleteUser1", "Delete")" method="post">
                                            <input type="hidden" name="Id" value="@Model.Id" />
                                            <input type="hidden" name="Password" value="@Model.Password" />
                                            @Html.AntiForgeryToken()
                                            <button type="submit" class="dropdown-item">
                                                <i class="bi bi-trash-fill"></i> Delete Profile
                                            </button>
                                        </form>
                                    </li>
                                    <li>
                                        <form action="@Url.Action("Logout", "Logout")">
                                            @Html.AntiForgeryToken()
                                            <button type="submit" class="dropdown-item">
                                                <i class="bi bi-arrow-left-square-fill"></i> Logout
                                            </button>
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>


    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MY MongoDB APP - <a asp-area="" asp-controller="Privacy" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MongoApp/Views/Shared/_AlterLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UserAuthCaller</title>
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MongoApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Login">ADMIN</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
                        aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarContent">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Login" title="Home">
                                <i class="bi bi-house-fill"></i> Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Privacy" asp-action="Privacy" title="Privacy Policy">
                                <i class="bi bi-shield-fill-exclamation"></i> Privacy
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="GetAllUser"  asp-action="GetAllUser" title="All Users">
                                <i class="bi bi-people-fill"></i> Users
                            </a>
                        </li>
                    </ul>
                    
                    <!-- Wrap the dropdown li element with a div and apply ms-auto class -->
                    <div class="ms-auto">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown"
                                   aria-expanded="false" title="User Actions">
                                    <img src="\profile.jpg" style="width: 50px; height: 50px; border-radius: 70%;">
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="userDropdown">
                                    <li>
                                        <form action="@Url.Action("UpdateUser1", "Update")" method="post">
                                            <input type="hidden" name="Id" value="@Model.Id" />
                                            <input type="hidden" name="UserName" value="@Model.UserName" />
                                            <input type="hidden" name="Age" value="@Model.Age" />
                                            <input type="hidden" name="Name" value="@Model.Name" />
                                            <input type="hidden" name="Email" value="@Model.Email" />
                                            <input type="hidden" name="Phonenumber" value="@Model.Phonenumber" />
                                            <input type="hidden" name="Password" value="@Model.Password" />
                                            <input type="hidden" name="Role" value="@Model.Role" />
                                            <input type="hidden" name="Status" value="@Model.Status" />
                                            @Html.AntiForgeryToken()
                                            <button type="submit" class="dropdown-item">
                                                <i class="bi bi-person-badge"></i> Edit Profile
                                            </button>
                                        </form>
                                    </li>
                                    <li>
                                        <form action="@Url.Action("UpdatePassword1", "Update")" method="post">
                                            <input type="hidden" name="Id" value="@Model.Id" />
                                            @Html.AntiForgeryToken()
                                            <button type="submit" class="dropdown-item">
                                                <i class="bi bi-key-fill"></i> Change Password
                                            </button>
                                        </form>
                                    </li>
                                    <li>
                                        <form action="@Url.Action("DeleteUser1", "Delete")" method="post">
                                            <input type="hidden" name="Id" value="@Model.Id" />
                                            <input type="hidden" name="Password" value="@Model.Password" />
                                            @Html.AntiForgeryToken()
                                            <button type="submit" class="dropdown-item">
                                                <i class="bi bi-trash-fill"></i> Delete Profile
                                            </button>
                                        </form>
                                    </li>
                                    <li>
                                        <form action="@Url.Action("Logout", "Logout")">
                                            @Html.AntiForgeryToken()
                                            <button type="submit" class="dropdown-item">
                                                <i class="bi bi-arrow-left-square-fill"></i> Logout
                                            </button>
                                        </form>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>


    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MY MongoDB APP - <a asp-area="" asp-controller="Privacy" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MongoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MongoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MongoApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Login">My MongoDB App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Privacy" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MY MongoDB App - <a asp-area="" asp-controller="Privacy" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>